DELETE http://localhost:3001/api/blogs/5a7c795eb373f1193c2c9c5b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2ludGVzdCIsImlkIjoiNWE3YzIwZDUzOTkwMmIxMjFiZTBhYTQ0IiwiaWF0IjoxNTE4MTA2NTk3fQ.kfSAWgvytS9JXSzVRdqv2vLs_Ep_kfHPvHN1RiKFuM0
